services:
  cache:
    image: redis:7-alpine
    restart: always
  api:
    image: airoapi
    restart: always
    ports:
      - 8080:8080
    environment:
      # All required fields
      ENDPOINT: <ENDPOINT> # e.g. "https://api.magicapi.dev/api/v1/aedbx/aerodatabox"
      API_KEY: <API_KEY>
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on: 
      - cache