name = "airoapi"
main = "build/index.js"
compatibility_date = "2026-02-01"

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release"

[[routes]]
pattern = "airoapi.tuxy.stream"
custom_domain = true
